USE plataforma_clases; 
-- Usar Base de Datos
SET NAMES utf8mb4;
-- Poder usar acentos y ñ en los nombres
INSERT INTO paises (pais) VALUES
('Afganistán'), ('Albania'), ('Alemania'), ('Andorra'), ('Angola'),
('Antigua y Barbuda'), ('Arabia Saudita'), ('Argelia'), ('Argentina'), ('Armenia'),
('Australia'), ('Austria'), ('Azerbaiyán'), ('Bahamas'), ('Bangladés'),
('Barbados'), ('Baréin'), ('Bélgica'), ('Belice'), ('Benín'),
('Bielorrusia'), ('Birmania'), ('Bolivia'), ('Bosnia y Herzegovina'), ('Botsuana'),
('Brasil'), ('Brunéi'), ('Bulgaria'), ('Burkina Faso'), ('Burundi'),
('Bután'), ('Cabo Verde'), ('Camboya'), ('Camerún'), ('Canadá'),
('Catar'), ('Chad'), ('Chile'), ('China'), ('Chipre'),
('Ciudad del Vaticano'), ('Colombia'), ('Comoras'), ('Corea del Norte'), ('Corea del Sur'),
('Costa de Marfil'), ('Costa Rica'), ('Croacia'), ('Cuba'), ('Dinamarca'),
('Dominica'), ('Ecuador'), ('Egipto'), ('El Salvador'), ('Emiratos Árabes Unidos'),
('Eritrea'), ('Eslovaquia'), ('Eslovenia'), ('España'), ('Estados Unidos'),
('Estonia'), ('Esuatini'), ('Etiopía'), ('Filipinas'), ('Finlandia'),
('Fiyi'), ('Francia'), ('Gabón'), ('Gambia'), ('Georgia'),
('Ghana'), ('Granada'), ('Grecia'), ('Guatemala'), ('Guinea'),
('Guinea-Bisáu'), ('Guinea Ecuatorial'), ('Guyana'), ('Haití'), ('Honduras'),
('Hungría'), ('India'), ('Indonesia'), ('Irak'), ('Irán'),
('Irlanda'), ('Islandia'), ('Islas Marshall'), ('Islas Salomón'), ('Israel'),
('Italia'), ('Jamaica'), ('Japón'), ('Jordania'), ('Kazajistán'),
('Kenia'), ('Kirguistán'), ('Kiribati'), ('Kuwait'), ('Laos'),
('Lesoto'), ('Letonia'), ('Líbano'), ('Liberia'), ('Libia'),
('Liechtenstein'), ('Lituania'), ('Luxemburgo'), ('Macedonia del Norte'), ('Madagascar'),
('Malasia'), ('Malaui'), ('Maldivas'), ('Malí'), ('Malta'),
('Marruecos'), ('Mauricio'), ('Mauritania'), ('México'), ('Micronesia'),
('Moldavia'), ('Mónaco'), ('Mongolia'), ('Montenegro'), ('Mozambique'),
('Namibia'), ('Nauru'), ('Nepal'), ('Nicaragua'), ('Níger'),
('Nigeria'), ('Noruega'), ('Nueva Zelanda'), ('Omán'), ('Países Bajos'),
('Pakistán'), ('Palaos'), ('Palestina'), ('Panamá'), ('Papúa Nueva Guinea'),
('Paraguay'), ('Perú'), ('Polonia'), ('Portugal'), ('Reino Unido'),
('República Centroafricana'), ('República Checa'), ('República del Congo'), ('República Democrática del Congo'), ('República Dominicana'),
('Ruanda'), ('Rumanía'), ('Rusia'), ('Samoa'), ('San Cristóbal y Nieves'),
('San Marino'), ('San Vicente y las Granadinas'), ('Santa Lucía'), ('Santo Tomé y Príncipe'), ('Senegal'),
('Serbia'), ('Seychelles'), ('Sierra Leona'), ('Singapur'), ('Siria'),
('Somalia'), ('Sri Lanka'), ('Sudáfrica'), ('Sudán'), ('Sudán del Sur'),
('Suecia'), ('Suiza'), ('Surinam'), ('Tailandia'), ('Tanzania'),
('Tayikistán'), ('Timor Oriental'), ('Togo'), ('Tonga'), ('Trinidad y Tobago'),
('Túnez'), ('Turkmenistán'), ('Turquía'), ('Tuvalu'), ('Ucrania'),
('Uganda'), ('Uruguay'), ('Uzbekistán'), ('Vanuatu'), ('Venezuela'),
('Vietnam'), ('Yemen'), ('Yibuti'), ('Zambia'), ('Zimbabue');

INSERT INTO comunas (comuna) VALUES
('Alhué'), ('Alto Biobío'), ('Alto del Carmen'), ('Alto Hospicio'), ('Ancud'),
('Andacollo'), ('Angol'), ('Antofagasta'), ('Antuco'), ('Arauco'),
('Arica'), ('Aysén'), ('Buin'), ('Bulnes'), ('Cabildo'),
('Cabo de Hornos'), ('Cabrero'), ('Calama'), ('Calera de Tango'), ('Calle Larga'),
('Camarones'), ('Camiña'), ('Canela'), ('Cañete'), ('Carahue'),
('Cartagena'), ('Casablanca'), ('Castro'), ('Catemu'), ('Cauquenes'),
('Cerrillos'), ('Cerro Navia'), ('Chaitén'), ('Chañaral'), ('Chépica'),
('Chiguayante'), ('Chile Chico'), ('Chillán'), ('Chillán Viejo'), ('Chimbarongo'),
('Chonchi'), ('Cisnes'), ('Coblemu'), ('Cochamó'), ('Cochrane'),
('Codegua'), ('Coelemu'), ('Coihueco'), ('Coincos'), ('Colbún'),
('Colchane'), ('Colina'), ('Collipulli'), ('Coltauco'), ('Combarbalá'),
('Concepción'), ('Conchalí'), ('Concón'), ('Constitución'), ('Contulmo'),
('Copiapó'), ('Coquimbo'), ('Coronel'), ('Corral'), ('Cunco'),
('Curacautín'), ('Curacaví'), ('Curaco de Vélez'), ('Curanilahue'), ('Curarrehue'),
('Curepto'), ('Curicó'), ('Diego de Almagro'), ('Doñihue'), ('El Bosque'),
('El Carmen'), ('El Monte'), ('El Quisco'), ('El Tabo'), ('Empedrado'),
('Ercilla'), ('Estación Central'), ('Florida'), ('Freire'), ('Freirina'),
('Fresia'), ('Frutillar'), ('Futaleufú'), ('Futrono'), ('Galvarino'),
('General Lagos'), ('Gorbea'), ('Graneros'), ('Guaitecas'), ('Hijuelas'),
('Hualaihué'), ('Hualañé'), ('Hualpén'), ('Hualqui'), ('Huara'),
('Huasco'), ('Huechuraba'), ('Illapel'), ('Iquique'), ('Isla de Maipo'),
('Isla de Pascua'), ('Juan Fernández'), ('La Calera'), ('La Cisterna'), ('La Cruz'),
('La Estrella'), ('La Florida'), ('La Granja'), ('La Higuera'), ('La Ligua'),
('La Pintana'), ('La Reina'), ('Laja'), ('Lampa'), ('Lanco'),
('Las Cabras'), ('Las Condes'), ('Lautaro'), ('Lebu'), ('Licantén'),
('Limache'), ('Linares'), ('Litueche'), ('Llanquihue'), ('Llay-Llay'),
('Lo Barnechea'), ('Lo Espejo'), ('Lo Prado'), ('Lolol'), ('Loncoche'),
('Longaví'), ('Lonquimay'), ('Los Álamos'), ('Los Andes'), ('Los Ángeles'),
('Los Lagos'), ('Los Muermos'), ('Los Vilos'), ('Lota'), ('Lumaco'),
('Machalí'), ('Macul'), ('Máfil'), ('Maipú'), ('Malloa'),
('Marchigüe'), ('María Elena'), ('María Pinto'), ('Mariquina'), ('Maule'),
('Maullín'), ('Mejillones'), ('Melipeuco'), ('Melipilla'), ('Molina'),
('Monte Patria'), ('Mostazal'), ('Mulchén'), ('Nacimiento'), ('Nancagua'),
('Natales'), ('Navidad'), ('Negrete'), ('Ninhue'), ('Nogales'),
('Nueva Imperial'), ('Ñuñoa'), ('O\'Higgins'), ('Olmué'), ('Osorno'),
('Ovalle'), ('Padre Hurtado'), ('Padre Las Casas'), ('Paihuano'), ('Paillaco'),
('Paine'), ('Palena'), ('Palmilla'), ('Panguipulli'), ('Panquehue'),
('Papudo'), ('Paredones'), ('Parral'), ('Pedro Aguirre Cerda'), ('Pemuco'),
('Peñaflor'), ('Peñalolén'), ('Pencahue'),
('Penco'), ('Peralillo'), ('Perquenco'), ('Petorca'), ('Peumo'),
('Pica'), ('Pichidegua'), ('Pichilemu'), ('Pinto'), ('Pirque'),
('Pitrufquén'), ('Placilla'), ('Portezuelo'), ('Porvenir'), ('Pozo Almonte'),
('Primavera'), ('Providencia'), ('Puchuncaví'), ('Pucón'), ('Pudahuel'),
('Puente Alto'), ('Puerto Montt'), ('Puerto Octay'), ('Puerto Varas'), ('Pumanque'),
('Punia'), ('Punitaqui'), ('Punta Arenas'), ('Puqueldón'), ('Purén'),
('Purranque'), ('Putaendo'), ('Putre'), ('Puyehue'), ('Queilén'),
('Quellón'), ('Quemchi'), ('Quilicura'), ('Quilleco'), ('Quillón'),
('Quillota'), ('Quilpué'), ('Quinchao'), ('Quinta de Tilcoco'), ('Quinta Normal'),
('Quintero'), ('Quirihue'), ('Rancagua'), ('Ránquil'), ('Rauco'),
('Recoleta'), ('Renaico'), ('Rencas'), ('Rengo'), ('Requínoa'),
('Retiro'), ('Rincónada'), ('Río Bueno'), ('Río Claro'), ('Río Hurtado'),
('Río Ibáñez'), ('Río Negro'), ('Río Verde'), ('Romeral'), ('Saavedra'),
('Sagrada Familia'), ('Salamanca'), ('San Antonio'), ('San Bernardo'), ('San Carlos'),
('San Clemente'), ('San Esteban'), ('San Fabián'), ('San Felipe'), ('San Fernando'),
('San Gregorio'), ('San Ignacio'), ('San Javier'), ('San Joaquín'), ('San José de Maipo'),
('San Juan de la Costa'), ('San Miguel'), ('San Nicolás'), ('San Pablo'), ('San Pedro'),
('San Pedro de Atacama'), ('San Pedro de la Paz'), ('San Rafael'), ('San Ramón'), ('San Rosendo'),
('San Vicente'), ('Santa Bárbara'), ('Santa Cruz'), ('Santa Juana'), ('Santa María'),
('Santiago'), ('Santo Domingo'), ('Sierra Gorda'), ('Talagante'), ('Talca'),
('Talcahuano'), ('Taltal'), ('Temuco'), ('Teno'), ('Teodoro Schmidt'),
('Tierra Amarilla'), ('Tiltil'), ('Tirúa'), ('Tocopilla'), ('Toltén'),
('Tomé'), ('Torres del Paine'), ('Tortel'), ('Traiguén'), ('Treguaco'),
('Tucapel'), ('Valdivia'), ('Vallenar'), ('Valparaíso'), ('Vichuquén'),
('Victoria'), ('Vicuña'), ('Vilcún'), ('Villa Alegre'), ('Villa Alemana'),
('Villarrica'), ('Viña del Mar'), ('Vitacura'), ('Yerbas Buenas'), ('Yumbel'),
('Yungay'), ('Zapallar');
