insert into paises (pais) values('Chile'),
('Argentina'),
('Perú'),
('Bolivia'),
('Brasil'),
('Uruguay'),
('Paraguay'),
('Colombia'),
('Ecuador'),
('Venezuela'),
('México'),
('Estados Unidos'),
('Canadá'),
('España'),
('Francia'),
('Alemania'),
('Italia'),
('Reino Unido'),
('Australia'),
('Japón')
